name: Build and Deploy
on:
  pull_request:
    branches:
      - staging

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Adjust to your Laravel version
          extensions: mbstring, bcmath, pdo, mysql, curl
          tools: composer, phpunit

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader

      # Step 4: Run tests
      - name: Run tests
        run: |
          php artisan test

      # Step 5: Deploy if tests pass
      - name: Deploy to api-staging.divineglobalgrowth.com
        if: success()
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/staging-api.divineglobalgrowth.com/savings-backend
            git pull origin staging
            cp .env .env.backup
            cp .env.staging .env
            composer install --optimize-autoloader --no-dev
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
            php artisan route:cache
            php artisan view:cache
            echo "Deployment successful!"
