name: Deploy
on:
  pull_request:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Application
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test SSH Connection
        run: |
          echo "Testing SSH connection on port 21098..."
          ssh -p 21098 -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@$${{ secrets.SERVER_DOMAIN }} "echo 'SSH connection successful'"

      - name: Deploy Application
        run: |
          echo "Starting deployment..."
          ssh -p 21098 -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@$${{ secrets.SERVER_DOMAIN }} 'bash -s' < ${{ github.workspace }}/.github/workflows/deploy.sh
