name: Deploy
on:
  pull_request:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Application
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check SSH Connection
        run: |
          echo "Testing SSH connection..."
          ssh -o StrictHostKeyChecking=no syncflux@${{ secrets.SERVER_IP }} "echo 'SSH connection successful'"

      - name: Deploy
        run: |
          echo "Starting deployment..."
          ssh -o StrictHostKeyChecking=no syncflux@${{ secrets.SERVER_IP }} 'bash -s' < ${{ github.workspace }}/.github/workflows/deploy.sh
