name: Deploy
on:
  push:
  pull_request:
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Application
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no syncflux@${{ secrets.SERVER_IP }} 'bash -s' < ${{ github.workspace }}/.github/workflows/deploy.sh
