name: Test

on:
  pull_request:
    branches:
      - staging

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: savings_test
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, mysql, curl
          tools: composer, phpunit

      - name: Create or copy .env
        env:
          DOT_ENV: ${{ secrets.DOT_ENV_DEV }}
        run: |
          touch .env
          echo "$DOT_ENV" | tee .env
          php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Configure database for testing
        run: |
          php artisan migrate --seed

      - name: Run tests
        run: |
          php artisan test
