name: Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            # Navigate to the project directory
            cd ~/api.divineglobalgrowth.com/savings-backend

            # Ensure the directory is a git repository
            if [ ! -d .git ]; then
              git init
              git remote add origin https://github.com/savings-backend.git
            fi

            # Pull the latest code from the main branch
            git fetch origin
            git reset --hard origin/main

            # Backup existing .env file
            if [ -f .env ]; then
              cp .env .env.backup
            fi

            # Install dependencies and optimize the Laravel application

            composer install --optimize-autoloader --no-dev
            php artisan key:generate
            php artisan migrate --force
            php artisan db:seed
            php artisan scribe:generate
            php artisan cache:clear
            php artisan route:cache
            php artisan view:cache

            echo "Deployment successful!"
