name: Deploy

on:
  push:
    branches:
      - staging

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/staging-api.divineglobalgrowth.com/savings-backend
            git pull origin staging
            composer install --optimize-autoloader --no-dev
            php artisan migrate
            php artisan key:generate
            php artisan db:seed
            php artisan scribe:generate
            php artisan cache:clear
            php artisan route:cache
            php artisan view:cache
            echo "Deployment successful!"
